version: 0.2

phases:
  install:
    commands:
      - (cd ./node && yarn install --frozen-lockfile --non-interactive)
  pre_build:
    commands:
      - ls -a
      - mkdir -p $GOPATH/src/github.com/tfrcm/playground-sls
      - mv * $GOPATH/src/github.com/tfrcm/playground-sls/.
      - cd $GOPATH/src/github.com/tfrcm/playground-sls
      - ls -a
      - echo pwd \"$(pwd)\"
      - echo BRANCH $BRANCH
      - echo GOPATH $GOPATH
      - echo node \"$(node -v)\"
      - echo yarn \"$(yarn --version)\"
      - echo python \"$(python3 --version)\"
      - echo awscli \"$(aws --version)\"
      - echo yarn cache dir \"$(yarn cache dir)\"
      - echo sls version \"$(sls version)\"
      - echo go version \"$(go version)\"
      - echo go env \"$(go env)\"
  build:
    commands:
      - echo $BRANCH
      - pwd
      - cd ./go
      - pwd
      - ls -a
      - make deploy-master
      # - |
      #   (
      #     cd ./go
      #     if [ "${BRANCH}" == "develop" ]; then
      #       make deploy OPT_BRANCH=develop
      #     elif [ "${BRANCH}" == "release" ]; then
      #       make deploy OPT_BRANCH=release
      #     elif [ "${BRANCH}" == "master" ]; then
      #       make deploy OPT_BRANCH=master
      #     else
      #       echo 'skip serverless Go deploy'
      #     fi
      #   )
