service: tfrcm-playground-sls-node

frameworkVersion: '>=1.28.0 <2.0.0'

custom:
  projectName: tfrcm-palyground
  defaultStage: local
  stage:
    local: ${file(./../stage/local.yml)}
    develop: ${file(./../stage/develop.yml)}
    release: ${file(./../stage/release.yml)}
    master: ${file(./../stage/master.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  environment:
    TZ: Asia/Tokyo
    PROJECT_NAME: ${self:custom.projectName}
    REGION: ${self:provider.region}
    STAGE: ${self:custom.stage.${self:provider.stage}.stage}
    HOST: ${self:custom.stage.${self:provider.stage}.host}
    PREFIX: ${self:custom.stage.${self:provider.stage}.prefix}
    DATABASE_HOST: ${self:custom.stage.${self:provider.stage}.database.host}
    DATABASE_USER: ${self:custom.stage.${self:provider.stage}.database.user}
    DATABASE_PASSWORD: ${self:custom.stage.${self:provider.stage}.database.password}
    DATABASE_NAME: ${self:custom.stage.${self:provider.stage}.database.database}
    LOG_LEVEL: ${self:custom.stage.${self:provider.stage}.logLevel}

functions:
  hello:
    handler: src/handlers/hello.hello
    events:
      - http:
          path: hello
          method: get
