service: tfrcm-playground-sls-node

frameworkVersion: '>=1.28.0 <2.0.0'

custom:
  projectName: tfrcm-palyground
  defaultStage: local
  stage:
    local: ${file(./../stage/local.yml)}
    develop: ${file(./../stage/develop.yml)}
    release: ${file(./../stage/release.yml)}
    master: ${file(./../stage/master.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: us-east-1
  memorySize: 128
  timeout: 1

functions:
  hello:
    handler: src/handlers/hello.hello
    events:
      - http:
          path: hello
          method: get
  edge:
    handler: src/handlers/edge.edge
